### PR TITLE
MTG mods, mobs, mobs_animals

### PR DESCRIPTION
**Pull request by sirrobzeroone**
Minetest Base Game finished
Sorted images into folder
Created images for Dye, Fire, Creative, Farming tools only, Xpanes mods

### CODE REVIEW

**Comment by sirrobzeroone** [comment]
resynced with main, wasn't real sure on the hotbar myself :)

**Comment by starninjas** [comment]
Nice update, I'm really liking the mobs!
Here are the textures that I'm not going to merge in, because I don't feel they fit the style well enough:
-Dyes
-Furnace tweaks
-Mob net

**Comment by sirrobzeroone** [comment]
All good with me, glad some are useful :)

**Comment by sirrobzeroone** [comment]
Okay that should hopefully make it easier, just removed the dyes/net for now and reverted the furnace :)

**Comment by starninjas** [comment]
Thanks a ton!

**Pull request merged**
